variable "env" {}
variable "tags" {}
variable "vpc_id" {}
variable "app_name" {}
variable "sg_port" {}
variable "ssh_ingress_cidr" {}
variable "sg_ingress_cidr" {}
variable "ami_id" {}
variable "instance_type" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_capacity" {}
variable "subnet_id" {}