variable "env" {}
variable "tags" {}
variable "vpc_id" {}
variable "app_name" {}
variable "sg_port" {}
variable "ssh_ingress_cidr" {}
variable "sg_ingress_cidr" {}
variable "ami_id" {}
variable "instance_type" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_capacity" {}
variable "subnet_id" {}
variable "zone_id" {}
variable "public_dns_record" {}
variable "private_dns_record" {}
variable "priority" {}
variable "private_listener_arn" {}
variable "public_listener_arn" {}
variable "default_vpc_id" {}
variable "prometheus_private_ip" {}
variable "kms_key" {}
variable "parameters" {}